spring.application.name=libreria

# Database H2   --usato in precdenza per i test prima di implementare postgres
#spring.datasource.url=jdbc:h2:mem:library;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
# H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/libreria
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
